#ifndef TENSORFLOW_CORE_PUBLIC_RELEASE_VERSION_H_
#define TENSORFLOW_CORE_PUBLIC_RELEASE_VERSION_H_

#define TF_MAJOR_VERSION 2
#define TF_MINOR_VERSION 14
#define TF_PATCH_VERSION 0
#define TF_VERSION_SUFFIX ""

#define _TF_STR(s) #s
#define TF_STR(s) _TF_STR(s)

#define TF_VERSION_STRING \
    (TF_STR(TF_MAJOR_VERSION) "." TF_STR(TF_MINOR_VERSION) "." TF_STR( \
        TF_PATCH_VERSION) TF_VERSION_SUFFIX)

#endif  // TENSORFLOW_CORE_PUBLIC_RELEASE_VERSION_H_ 