set(TF_MAJOR_VERSION "2")
set(TF_MINOR_VERSION "14")
set(TF_PATCH_VERSION "0")
set(TF_VERSION_SUFFIX "")

add_definitions(-DTF_MAJOR_VERSION=${TF_MAJOR_VERSION})
add_definitions(-DTF_MINOR_VERSION=${TF_MINOR_VERSION})
add_definitions(-DTF_PATCH_VERSION=${TF_PATCH_VERSION})
add_definitions(-DTF_VERSION_SUFFIX="${TF_VERSION_SUFFIX}") 